# Generated by Django 2.0 on 2018-09-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20180923_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='to_user',
            new_name='to_user_id',
        ),
    ]
