# Generated by Django 2.0 on 2018-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_archives_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archives',
            new_name='Dynamics',
        ),
    ]
