# Generated by Django 2.0 on 2018-10-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20181007_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='anonymous',
            field=models.BooleanField(default=True, verbose_name='是否匿名'),
        ),
    ]
