# Generated by Django 2.0 on 2018-10-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_message_anonymous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
    ]
