# Generated by Django 2.0 on 2018-09-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180921_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/user/default/1.png', upload_to='image/user/%Y/%m', verbose_name='头像'),
        ),
    ]
