# Generated by Django 2.0 on 2018-09-21 18:55

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180921_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gitee',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='码云地址'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='GitHub地址'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='个人简介'),
        ),
    ]
