# Generated by Django 2.0 on 2018-09-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180922_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
