# Generated by Django 2.0 on 2019-02-04 14:44

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='文章内容')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='文章简介')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('view_nums', models.IntegerField(default=0, verbose_name='浏览数')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('like_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('tags', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('title', models.CharField(max_length=100, verbose_name='分类标题')),
                ('info', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('lines', models.TextField()),
            ],
            options={
                'verbose_name': '定场诗',
                'verbose_name_plural': '定场诗',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='分类'),
        ),
    ]
