# Generated by Django 2.0 on 2018-10-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180923_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='封面图地址'),
        ),
    ]
