# Generated by Django 2.0 on 2018-10-11 19:36

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='文章内容'),
        ),
    ]
