# Generated by Django 2.0 on 2018-10-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20181011_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='image/article/default/0.png', max_length=100, verbose_name='封面图地址'),
        ),
    ]
