# Generated by Django 2.0 on 2018-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20181012_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='http://127.0.0.1:8000/media/image/article/default/0.png', max_length=100, verbose_name='封面图地址'),
        ),
    ]
