# Generated by Django 2.0 on 2018-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20181012_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
