# Generated by Django 2.0 on 2018-10-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag标签'),
        ),
    ]
