# Generated by Django 2.0 on 2018-10-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profile',
            field=models.TextField(blank=True, null=True, verbose_name='文章简介'),
        ),
    ]
