# Generated by Django 2.0 on 2018-10-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='http://47.98.207.4/media/image/article/default/0.png', max_length=100, verbose_name='封面图地址'),
        ),
    ]
